Ninja Glove Stun Reduced To Match Flash
ss14-harmony/ss14-harmony pull request #220
Opened 2024-11-30 08:23 UTC by DieselMohawk

## About the PR
 Reduced the stun timer on the stun component to match the flash

## Why / Balance
 The stun is likely intended to be for disengagement and disarming crew, but currently it's used to instantly stun cuff or kill people. It's a VERY aggressive tool for a supposedly sneaky antagonist.

## Technical details

## Media

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Ninja Stun Reduced to fit Flash stun time.

2024-11-30 10:29 UTC, FluffMe requested changes
Both changes require a harmony change comment on the same line.

2024-11-30 11:01 UTC, DieselMohawk commented
> Both changes require a harmony change comment on the same line.

Whoops, did this while tired, I'll do that tomorrow.

2024-11-30 19:38 UTC, TheCrimsonJupiter commented
"Time that someone is stunned for, stacks if done multiple times." If this is the case the recharge time for the gloves should be longer than the stun time itself to avoid stun-locking. I think an infinite stun-lock would defeat the purpose of making this change in the first place.

2024-11-30 19:58 UTC, DieselMohawk commented
> "Time that someone is stunned for, stacks if done multiple times." If this is the case, the recharge time for the gloves should be longer than the stun time itself to avoid stun-locking. I think an infinite stun-lock would defeat the purpose of making this change in the first place.

Fair, I'll adjust it when I can

2024-12-02 22:43 UTC, FluffMe requested changes

2024-12-02 22:43 UTC, FluffMe commented on Content.Shared/Ninja/Components/StunProviderComponent.cs
> +    public TimeSpan StunTime = TimeSpan.FromSeconds(1.5);
Also needs a comment now.

2024-12-02 23:01 UTC, FluffMe requested changes
- `Cooldown` is back to Upstream 2 so it doesn't require a comment.
- Someone should really test this on Dev.

2024-12-02 23:01 UTC, FluffMe commented on Content.Shared/Ninja/Components/StunProviderComponent.cs
> +    public TimeSpan Cooldown = TimeSpan.FromSeconds(2); // Harmony: Stun cooldown changed to prevent stunlocking
This value is now unchanged from upstream.
Either a mistake, or comment should be removed?

2024-12-15 17:53 UTC, DieselMohawk commented
Oh, I forgot about this, were getting some testing with the ninja upstream so I'm gonna wait for that.

2025-02-01 00:12 UTC, DieselMohawk commented
Reopened at the request of CrimsonJupiter

2025-02-01 00:15 UTC, DieselMohawk commented
Also, the upstream merge did not happen

2025-02-05 03:25 UTC, Zap527 approved these changes
Approved by the admin team.

2025-02-05 16:46 UTC, merged