PDA messaging Port
ss14-harmony/ss14-harmony pull request #245
Opened 2024-12-25 17:50 UTC by Ermucat

## About the PR

Added the new app Nanochat, allowing crewmembers to chat if given their nanochat ID
## Why / Balance

This gives traitors a new way of exchanging information instead of just sitting a corner, adds depth, and potential to be utilized
## Technical details

Changed LogProbe UI and system
Changed Agent ID UI and system
Added DeltaV folders for Content.Server,Content.Client,Content.Shared
Added new nanochat ui
Added new nanochat system
added new nanochat components
## Media

Stamd by while I fix my internet and upload the video
## Requirements

- [ X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added a new program to your pda, nanochat!

2024-12-25 23:21 UTC, FluffMe requested changes
After first quick glance:

- Test fail is real: https://github.com/ss14-harmony/space-station-14/actions/runs/12495369896/job/34869788588?pr=245#step:10:15
    Please fix it
- All `DeltaV` folders should be `_DeltaV` instead

2024-12-25 23:43 UTC, FluffMe commented
FYI, you can run the tests locally, not on github. So that you can fix everything before you push and be mostly sure that it's fixed.

The command to run the test is listed in the test: https://github.com/ss14-harmony/space-station-14/actions/runs/12495369896/job/34869788588#step:10:3 on the example of Integration tests.

Currently even Build fails, so please test changes before pushing them.

2024-12-25 23:58 UTC, FluffMe requested changes
Not sure why the review popped again, but:
- Linter fails
- Build fails
- Tests fail

It got worse. Please fix before requesting review.

I am drafting this. Please undraft when it's in ready and test passing state.

2024-12-26 00:07 UTC, FluffMe commented
Why is this undrafted?

2024-12-26 00:39 UTC, FluffMe commented
Same test fail. Please don't undraft until you fix this.
Run tests locally with

```bash
dotnet test --no-build --configuration DebugOpt Content.IntegrationTests/Content.IntegrationTests.csproj -- NUnit.ConsoleOut=0 NUnit.MapWarningTo=Failed
```

2024-12-26 00:43 UTC, Ermucat commented
It is claiming that it cant find Content.Integratiotests/Content.Intergrationtests.dll when I run the command

2024-12-26 00:46 UTC, FluffMe commented
> It is claiming that it cant find Content.Integratiotests/Content.Intergrationtests.dll when I run the command

- You must build the project first (launching the dev build should include building). Or remove `--no-build` flag to build.
- Command should be executed in the folder of the repo with the branch checked out.

2024-12-26 01:39 UTC, Ermucat commented
![image](https://github.com/user-attachments/assets/a6f3c6c3-0ba7-4bbe-b26a-4e090d0291d2)

I think something had gone very wrong. what do I do?

2024-12-26 04:59 UTC, FluffMe commented
> ![image](https://private-user-images.githubusercontent.com/190304574/398612151-a6f3c6c3-0ba7-4bbe-b26a-4e090d0291d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxODg5NjIsIm5iZiI6MTczNTE4ODY2MiwicGF0aCI6Ii8xOTAzMDQ1NzQvMzk4NjEyMTUxLWE2ZjNjNmMzLTBiYTctNGJiZS1iMjZhLTRlMDkwZDAyOTFkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwNDUxMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmRlYmMxN2MwNGNhY2E2ZGUzOTM4ZDMwMGJlNjdhZWU2NDJiMDU2M2E3MTYxMThjMTIzMWQ1NDdjMGY2ODYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.m-5ALcNaRHyot2s5LmZl6aup3jXh7WxySaOMIxyxkrM)
> 
> I think something has gone very wrong. what do I do?
> 
> Okay so Ive reverted to the orignal commit "It is finished" this has fixed the issue, now its just res.typecheck: Sandbox violation: Access to type not allowed: [Content.Shared]AgentIDCardJobIconChangedMessage

In `Content.Shared/Access/SharedAgentIDCardSystem.cs` (https://github.com/ss14-harmony/space-station-14/blob/b7b33590368bd12bb403830e369dd82cd77682b0/Content.Shared/Access/SharedAgentIDCardSystem.cs) you define the following on lines `87-119`:
- `AgentIDCardNameChangedMessage` 
- `AgentIDCardJobChangedMessage`
- `AgentIDCardJobIconChangedMessage`

This file already has defined:
- `AgentIDCardNameChangedMessage` on line 55 -- https://github.com/ss14-harmony/space-station-14/blob/b7b33590368bd12bb403830e369dd82cd77682b0/Content.Shared/Access/SharedAgentIDCardSystem.cs#L55
- `AgentIDCardJobChangedMessage` on line 66 -- https://github.com/ss14-harmony/space-station-14/blob/b7b33590368bd12bb403830e369dd82cd77682b0/Content.Shared/Access/SharedAgentIDCardSystem.cs#L66
- `AgentIDCardJobIconChangedMessage` on line 77 -- https://github.com/ss14-harmony/space-station-14/blob/b7b33590368bd12bb403830e369dd82cd77682b0/Content.Shared/Access/SharedAgentIDCardSystem.cs#L77

All three of them are `sealed`, and trying to redeclare them might trigger the error you are seeing.
All three of them are identical to the ones you are added. So I have no idea why you did that, and you should remove it regardless of error or not.

Try it. See if tests pass.

2024-12-26 05:01 UTC, Ermucat commented
I will test this soon, thank you so much.

2024-12-26 05:14 UTC, FluffMe commented
If this doesn't help, dig deeper into anything that touches `AgentIDCardJobIconChangedMessage` in your code and compare it carefully to Milon's implementation. Might be `public` keyword missing somewhere or something else that is minor but that trips the type checker.

But _probably_ this is it.

2024-12-26 05:39 UTC, Ermucat commented
Alright so my test succeeded so hopefully this wont fail

2025-01-05 04:18 UTC, DieselMohawk submitted a review, later dismissed
Sprites look good.

2025-01-06 15:31 UTC, FluffMe requested changes
The PR has a mix of DeltaV namespaces (`DeltaV` and `_DeltaV`) in this PR that should be addressed.
DeltaV namespaces on harmony are `_DeltaV` and soon to be changed in bulk.

Please change all instances of `Content.Client.DeltaV...` `Content.Shared.DeltaV...` `Content.Client.DeltaV...` etc to `Content.Client._DeltaV...` `Content.Shared._DeltaV...` `Content.Client._DeltaV...` etc for an easier bulk change in the upcoming PR.

2025-01-07 15:25 UTC, FluffMe requested changes
- Unresolved merge conflict
- Please implement https://github.com/DeltaV-Station/Delta-v/pull/2565

2025-01-22 02:10 UTC, liltenhead commented
Not sure if this still needs admin approval or if its unclear, but it looks good

2025-02-02 07:48 UTC, DieselMohawk submitted a review, later dismissed

2025-05-22 20:29 UTC, Ermucat commented
beat you to it

2025-05-22 20:29 UTC, closed without merging