Make bonfires actually set you on fire
ss14-harmony/ss14-harmony pull request #255
Opened 2024-12-29 04:40 UTC by Ermucat

## About the PR

Bonfires now arent solid objects AND set you on fire
## Why / Balance

Bonfires being solid objects is weird, and they didnt set you on fire which was boring
## Technical details

Added Ignition Fixture to Bonfire
Added IgniteonCollid to Bonfire
Added TriggerOnCollide to Bonfire
## Media

https://github.com/user-attachments/assets/4816a344-1692-43f1-93a9-c213b7c5fd96

## Requirements

- [X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Bonfires now set you on fire, watch your step.

2024-12-30 20:06 UTC, FluffMe requested changes
Commenting required.

Otherwise looks good (implying that you thoroughly tested construction/deconstruction and new components behavior)

2024-12-30 20:06 UTC, FluffMe commented on Resources/Prototypes/Entities/Structures/Decoration/bonfire.yml
> +  - type: Fixtures
```suggestion
  # Harmony. Bonfire improvements below
  - type: TriggerOnCollide
    fixtureID: ignition
  - type: Fixtures
```

Upstream file change lacks comment. Add Harmony comment that explains the change before the `TriggerOnCollide` component

2024-12-30 20:06 UTC, FluffMe commented on Resources/Prototypes/_Harmony/Recipes/Construction/Graphs/machines/switching.yml
> +- type: constructionGraph
```suggestion
# Bonfire
- type: constructionGraph
```

2024-12-30 20:07 UTC, Ermucat commented
Last I checked construction and compontents work, but I quickly test again with your changes

2024-12-30 20:23 UTC, FluffMe commented
@Ermucat this is currently in Furniture category.
Perhaps, `Misc` is a better fit?

2024-12-30 20:27 UTC, Ermucat commented
Yep, also made files for it instead of jamming it in switching.yml and machines

2024-12-30 20:28 UTC, FluffMe approved these changes
LGTM

Points for admin discussion:
- Construction cost
- Refund on destruction
- Do you guys want it

2024-12-30 20:32 UTC, FluffMe requested changes
Another batch of changes after file structure change.

2024-12-30 20:32 UTC, FluffMe commented on Resources/Prototypes/_Harmony/Recipes/Construction/Graphs/machines/switching.yml
> +
```suggestion
```

Unnecessary change. Revert

2024-12-30 20:32 UTC, FluffMe commented on Resources/Prototypes/_Harmony/Recipes/Construction/machines.yml
> +
```suggestion
```

Unnecessary change. Revert

2024-12-30 20:32 UTC, FluffMe commented on Resources/Prototypes/_Harmony/Recipes/Construction/structures.yml
Just rename it to `Resources/Prototypes/_Harmony/Recipes/Construction/bonfire.yml` to match the constructuion graph.

2024-12-30 21:01 UTC, FluffMe approved these changes
LGTM

2025-01-23 21:36 UTC, merged

2025-01-23 21:36 UTC, KeldWolf commented
Confirmed looks good. Merged.